# This file tells Netlify how to build and deploy your site.

# 1. Frontend Build Settings
[build]
  command = "npm run build"
  publish = "dist"
  functions = "api"

# 2. API Rewrites
# The ":splat" is a placeholder that ensures the entire path after /api/
# is correctly passed to your Python function.
[[redirects]]
  from = "/api/:splat"
  to = "/.netlify/functions/index/:splat"
  status = 200

# 3. Frontend Catch-all Rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

