    # This file tells Netlify how to build and deploy your site.

    # 1. Frontend Build Settings
    [build]
      command = "npm run build"
      publish = "dist"
      # IMPORTANT: This tells Netlify that your functions are directly in the 'api' directory.
      # Netlify will then look for subdirectories within 'api' as individual functions.
      functions = "api" 

    # 2. API Rewrites
    # This rule tells Netlify to send any request starting with /api/
    # to your Python backend function named 'index'.
    # The ':splat' ensures all sub-paths are correctly passed.
    [[redirects]]
      from = "/api/*"
      to = "/.netlify/functions/index"
      status = 200

    # 3. Frontend Catch-all Rule
    [[redirects]]
      from = "/*"
      to = "/index.html"
      status = 200
    

